**1. 将 NumPy 导入为 np，并查看版本**

难度：L1 

问题：将 NumPy 导入为 np，并输出版本号。

In [3]:
import numpy as np
print(np.__version__)

c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.IPBC74C7KURV7CB2PKT5Z5FNR3SIBV4J.gfortran-win_amd64.dll
c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.JPIJNSWNNAN3CE6LLI5FWSPHUT2VXMTH.gfortran-win_amd64.dll
  stacklevel=1)


1.20.1


**2. 如何创建 1 维数组？** 

难度：L1 

问题：创建数字从 0 到 9 的 1 维数组。 

期望输出： 
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**3. 如何创建 boolean 数组？** 

难度：L1 

问题：创建所有 True 的 3×3 NumPy 数组。

In [16]:
#方法1
arr = np.array([1]*9,dtype=np.bool_).reshape(3,3)
#方法2
arr = np.full((3,3),True,dtype=np.bool_)
#方法3
arr = np.ones((3,3),dtype=np.bool_)
arr

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**4.如何从一维数组中提取满足给定条件的项？** 

难度：L1

问题：从 arr 中提取所有奇数。

输入：`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` 

期望输出：``array([1, 3, 5, 7, 9])``

In [19]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
np.where(arr%2!=0)

(array([1, 3, 5, 7, 9], dtype=int64),)

**5.如何将numpy数组中满足条件的项替换成另一个值？** 

难度等级：L1 

问题：将arr中所有的奇数替换为-1

输入：`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` 

期望输出：`array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])`


In [23]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**6.如何将numpy数组中满足条件的项替换成另一个值，而且不影响原始数组？** 

难度等级：L2 

问题：将arr中所有的奇数替换为-1，而无需更改 arr

输入：`arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` 

期望输出: 

out 

`array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])` 

arr 

`array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`


In [25]:
arr = np.arange(10)
out = np.where(arr%2!=0,-1,arr)
print(arr)
out

[0 1 2 3 4 5 6 7 8 9]


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**7.如何重塑数组？** 

难度等级：L1 

问题：将一维数组转换为具有两行的二维数组

输入：

`np.arange(10)` 

`#> array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])` 

期望的输出：

`#> array([[0, 1, 2, 3, 4],

#>        [5, 6, 7, 8, 9]])`

In [27]:
arr = np.arange(10)
arr.reshape(2,5)#arr.reshape(2,-1) -1表示指定行数后，程序自动设置列数

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**8.如何垂直堆叠两个数组？** 

难度等级：L2 

问题：垂直堆叠数组a和b 

输入： 

``a = np.arange(10).reshape(2,-1) 
 b = np.repeat(1, 10).reshape(2,-1)`` 

期望的输出：

#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])

In [42]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#方法一
c = np.concatenate([a,b],axis=0)

#方法二
c = np.vstack([a,b])

#方法三
c = np.r_[a, b]
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**9.如何水平堆叠两个数组？** 

难度等级：L2 

问题：水平堆叠数组a和b 

输入： 

`a = np.arange(10).reshape(2,-1) ` 

`b = np.repeat(1, 10).reshape(2,-1) ` 

期望输出： 

`#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],` 

`#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])`

In [43]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

#方法一
c = np.concatenate([a,b],axis=1)

#方法二
c = np.hstack([a,b])

#方法三
c = np.c_[a, b]
c

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**10.如何在不进行硬编码的情况下，在numpy中生成自定义序列？** 

难度等级：L2 

问题：不进行硬编码的情况下，创建以下模式。仅使用numpy函数和下面的输入数组a。 

输入：

`a = np.array([1,2,3])` 

期望的输出：

`#> array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])`

In [57]:
a = np.array([1,2,3])
np.r_[np.repeat(a,3),np.tile(a,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

**11.如何获取两个numpy数组的公共项？** 

难度等级：L2 

问题：获取数组a和数组b的公共项

输入：

`a = np.array([1,2,3,2,3,4,3,4,5,6])` 

`b = np.array([7,2,10,2,7,4,9,4,9,8])` 

期望的输出： 

`array([2, 4])`

In [59]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

**12.如何从一个数组中删除另一个数组中存在的那些项？** 

难度等级：L2 

问：从数组中a删除数组b中存在的共同项

输入：

`a = np.array([1,2,3,4,5])` 

`b = np.array([5,6,7,8,9])` 

期望的输出：

`array([1,2,3,4])`

In [65]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
np.setdiff1d(a,b)

array([1, 2, 3, 4])

**13.如何获得两个数组的元素匹配的位置？** 

难度等级：L2 

问：获取a和b匹配的位置

输入：

`a = np.array([1,2,3,2,3,4,3,4,5,6])` 

`b = np.array([7,2,10,2,7,4,9,4,9,8])` 

期望的输出： 


`#> (array([1, 3, 5, 7]),)`

**13.如何获得两个数组的相匹配元素的位置？** 

难度等级：L2 

问：获取a和b元素相匹配的位置 

输入：

`a = np.array([1,2,3,2,3,4,3,4,5,6])` 

`b = np.array([7,2,10,2,7,4,9,4,9,8])` 

期望的输出： 

`#> (array([1, 3, 5, 7]),)`

In [63]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

**14.如何从numpy数组中提取给定范围内的所有数字？** 

难度等级：L2 

问：从中数组a中获取5到10之间的所有项 

输入：

`a = np.array([2, 6, 1, 9, 10, 3, 27])` 

期望的输出： 

`（array（[ 6 ，9 ，10 ]），）`


In [80]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
print(type(a))

#方法1：
index = np.isin(a, np.arange(5,11))
a[index]

# 方法3：
index = np.where((a >= 5) & (a <= 10))
a[index]

# 方法3:
index = np.where(np.logical_and(a>=5, a<=10))
a[index]


# 方法4: (thanks loganzk!)
a[(a >= 5) & (a <= 10)]

<class 'numpy.ndarray'>


array([ 6,  9, 10])

**15.如何制作一个处理标量的python函数以在numpy数组上工作？** 

难度等级：L2 

问：将对两个标量起作用的函数maxx转换为对两个数组起作用 

输入：

/<code>
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
/</code>

期望的输出： 

/<code>
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
/</code>

In [87]:
def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max = np.vectorize(maxx, otypes=[float])
pair_max(a, b)

array([6., 7., 9., 8., 9., 7., 5.])

**16.如何在两维 numpy数组中交换两列？** 

难度等级：L2 

问：交换arr数组中的第1列和第2列。

输入： 

/<code>
arr = np.arange(9).reshape(3,3)
/</code> 

期望的输出： 

/<code>
array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])
/</code> 

In [97]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:,[1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

**17.如何交换二维numpy数组中的两行？** 

难度等级：L2 

问题：交换数组arr中的第1行和第2行：

```arr = np.arange(9).reshape(3,3)
arr```

In [99]:
arr = np.arange(9).reshape(3,3)
print(arr)
arr[[1,0,2],:]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

**18.如何反转2D数组的行？** 

难度等级：L2 

问：反转2D数组arr的行。

输入： 

```arr = np.arange(9).reshape(3,3)
arr
[[0 1 2]
 [3 4 5]
 [6 7 8]]```

期望的输出： 

```array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])```


In [101]:
arr = np.arange(9).reshape(3,3)
arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

**19.如何反转2D数组的列？** 

难度等级：L2 

问：反转2D数组arr的列。

输入： 

```arr = np.arange(9).reshape(3,3)
arr
[[0 1 2]
 [3 4 5]
 [6 7 8]]```

期望的输出： 

```#> array([[2, 1, 0],
        [5, 4, 3],
        [8, 7, 6]])```

In [104]:
arr = np.arange(9).reshape(3,3)
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

**20.如何创建一个包含5到10之间的随机浮点数的2D数组？** 

难度等级：L2 

问：创建一个形状为5x3的2D数组，以包含5到10之间的随机十进制数。

In [119]:
# 方法 1:
rand_arr = np.random.randint(low=5, high=10, size=(5,3)) + np.random.random((5,3))
print(rand_arr)

# 方法 2:
rand_arr = np.random.uniform(5,10, size=(5,3))
print(rand_arr)

[[9.99390671 6.59348571 7.71073234]
 [6.89846906 5.25972352 5.73728072]
 [7.34499805 7.16443203 8.37334441]
 [6.61613051 6.93669015 6.50058619]
 [9.23717864 6.07602763 8.85324086]]
[[9.69932335 9.90903109 7.34282408]
 [7.41741311 9.87318211 7.6986043 ]
 [6.46607236 5.29084503 8.61214674]
 [9.2290614  8.34204058 8.79906149]
 [6.34140602 9.86012432 6.91544042]]


In [120]:
arr = np.random.uniform(5,10,size=(5,3))
arr

array([[6.57965908, 8.86200376, 5.85241429],
       [5.79113381, 8.86717009, 5.67536708],
       [5.4070542 , 9.47323233, 6.79741606],
       [9.22002176, 6.8328602 , 9.73247235],
       [5.95403343, 9.3688248 , 8.29331962]])

**21.如何在python numpy数组中仅打印3个小数位？** 

难度等级：L1 

问：打印或仅显示numpy数组rand_arr的3个小数位

输入： 

`rand_arr = np.random.random((5,3))`

In [132]:
rand_arr = np.random.random((5,3))
np.set_printoptions(precision=3)
rand_arr

array([[0.833, 0.908, 0.207],
       [0.93 , 0.316, 0.461],
       [0.3  , 0.628, 0.865],
       [0.529, 0.895, 0.409],
       [0.108, 0.777, 0.295]])

**22.如何通过抑制科学计数法（如1e10）来漂亮地打印一个numpy数组？** 

难度等级：L1 

问：rand_arr压制科学记数法（如1e10）可以打印出漂亮的文字 

输入：

/<code>
#Create the random array
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

array([[  5.434049e-04,   2.783694e-04,   4.245176e-04],
        [  8.447761e-04,   4.718856e-06,   1.215691e-04],
        [  6.707491e-04,   8.258528e-04,   1.367066e-04]])
/</code> 

期望的输出： 


``` array([[ 0.000543,  0.000278,  0.000425],
        [ 0.000845,  0.000005,  0.000122],
       [ 0.000671,  0.000826,  0.000137]])```

In [136]:
np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
np.set_printoptions(suppress=True, precision=6)  # precision is optional
rand_arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

**23.如何限制numpy数组打印输出中的项目数？** 

难度等级：L1 

问：限制numpy数组a中打印的项目数最多为6个元素。

输入：

```
a = np.arange(15)
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]) ``` 

期望的输出： 

```
#> array([ 0,  1,  2, ..., 12, 13, 14])```

In [138]:
a = np.arange(15)
np.set_printoptions(threshold=6)
a

array([ 0,  1,  2, ..., 12, 13, 14])

**24.如何在不截断的情况下打印完整的numpy数组** 

难度等级：L1 

问：打印完整的numpy数组a而不被截断。

输入：

/<code>
np.set_printoptions(threshold=6)
a = np.arange(15)
a
#> array([ 0,  1,  2, ..., 12, 13, 14])
/<code> 
    
期望的输出：
```
a
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])```

In [151]:
np.set_printoptions(threshold=6)
a = np.arange(15)
np.set_printoptions(edgeitems=3, infstr='inf',
   linewidth=75, nanstr='nan', precision=8,
   suppress=False, threshold=1000, formatter=None)#恢复默认的设置
a
#np.set_printoptions(threshold=np.nan)
#a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

**25.如何导入带有数字和文本的数据集，以使numpy中的文本完整无缺？** 

难度等级：L2 

问题：导入鸢尾花数据集iris dataset，并保持文本完整无缺,链接=‘https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data’

In [156]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris  = np.genfromtxt(url,delimiter=',', dtype='object')#dtype='object',如果不设置，则文本就会导入到nan，所以为了保持文本完整就设置成object对象
np.set_printoptions(threshold=5)
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       ...,
       [b'6.5', b'3.0', b'5.2', b'2.0', b'Iris-virginica'],
       [b'6.2', b'3.4', b'5.4', b'2.3', b'Iris-virginica'],
       [b'5.9', b'3.0', b'5.1', b'1.8', b'Iris-virginica']], dtype=object)

**26.如何从一维元组数组中提取特定列？** 

难度等级：L2 

问：从导入的iris一维元组数组中提取文本列species 

输入：

/<code>
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
/<code>

In [160]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
species = np.array([row[4] for row in iris_1d])
species

c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', ...,
       b'Iris-virginica', b'Iris-virginica', b'Iris-virginica'],
      dtype='|S15')

**27.如何将一元组的一维数组转换为二维的numpy数组？** 

难度等级：L2 

问：通过省略文本字段species，将1Diris数组转换为2D数组iris_2d

输入：

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)```

In [172]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
#print(iris_1d)

iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d

c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:2: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  
c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       ...,
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

**28.如何计算一个numpy数组的均值，中位数，标准差？** 

难度：L1 

问：求出iris的sepallength列的均值，中位数，标准差（第一列）#names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

输入：

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')```

In [183]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float',usecols=(0))#np.array(iris[:,0],dtype='float')
mean,median,std = np.mean(sepallength),np.median(sepallength),np.std(sepallength)
print(f"mean:{mean},median:{median},std:{std}")

mean:5.843333333333334,median:5.8,std:0.8253012917851409


**29.如何规范化数组，以使值恰好在0到1之间？** 

难度：L2 

Q:创建归一化形式的iris的sepallength，其值范围恰好0与1之间，使得最小的值为0，并且最大的值为1。

输入：

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])```

In [189]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
smax,smin = np.max(sepallength),np.min(sepallength)
S = (sepallength-smin)/(smax-smin)
# or 
#S = (sepallength - smin)/sepallength.ptp()  # Thanks, David Ojeda!
print(S)

[0.22222222 0.16666667 0.11111111 ... 0.61111111 0.52777778 0.44444444]


**30.如何计算softmax分数？(L3)** 

问：计算sepallength的softmax得分 

输入： 

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])```

In [211]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

res = np.exp(sepallength)/np.sum(np.exp(sepallength))
np.set_printoptions(threshold=10)
print(res)

def softmax(x):
    """Compute softmax values for each sets of scores in x.
    https://stackoverflow.com/questions/34968722/how-to-implement-the-softmax-function-in-python"""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)
print(softmax(sepallength))

[0.00221959 0.00181724 0.00148783 ... 0.00900086 0.006668   0.00493978]
[0.00221959 0.00181724 0.00148783 ... 0.00900086 0.006668   0.00493978]


**31.如何找到一个numpy数组的百分位数？** 

难度等级：L1 

问：找到iris数据sepallength列的第5和第95百分位数

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])```

In [214]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
np.percentile(sepallength, q=[5,95])

array([4.6  , 7.255])

**32.如何在数组的随机位置插入值？** 

难度等级：L2 

问：在iris_2d数据集的20个随机位置插入值np.nan 

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')```

In [221]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
np.set_printoptions(threshold=1000)

np.random.seed(100)
iris_2d[np.random.randint(iris_2d.shape[0],size=20),np.random.randint(iris_2d.shape[1],size=20)]=np.nan
print(iris_2d[:10])

[[b'5.1' b'3.5' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.9' b'3.0' b'1.4' b'0.2' b'Iris-setosa']
 [b'4.7' b'3.2' b'1.3' b'0.2' b'Iris-setosa']
 [b'4.6' b'3.1' b'1.5' b'0.2' b'Iris-setosa']
 [b'5.0' b'3.6' b'1.4' b'0.2' b'Iris-setosa']
 [b'5.4' b'3.9' b'1.7' b'0.4' b'Iris-setosa']
 [b'4.6' b'3.4' b'1.4' b'0.3' b'Iris-setosa']
 [b'5.0' b'3.4' b'1.5' b'0.2' b'Iris-setosa']
 [b'4.4' b'2.9' nan b'0.2' b'Iris-setosa']
 [b'4.9' b'3.1' b'1.5' b'0.1' b'Iris-setosa']]


**33.如何在numpy数组中查找缺失值的位置？** 

难度等级：L2 

问：在iris_2d的sepallength（第1列）中找到缺失值的数量和位置

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan```

In [227]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float')
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

print("Number of missing values: \n", np.isnan(iris_2d[:, 0]).sum())
print("Position of missing values: \n", np.where(np.isnan(iris_2d[:, 0])))

Number of missing values: 
 6
Position of missing values: 
 (array([ 32,  40,  42,  71,  93, 101], dtype=int64),)


**34.如何根据两个或多个条件过滤一个numpy数组？** 

难度等级：L3 

问：筛选iris_2d第3列petallength > 1.5和第1列sepallength  < 5.0 的行

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])```

In [232]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#方法1：
condition = (iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)

#方法2：
condition = np.where(np.logical_and((iris_2d[:,2]>1.5),(iris_2d[:,0]<5.0)))

iris_2d[condition]

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

**35.如何从numpy数组中删除包含缺失值的行？** 

难度等级：L3：

问：选择没有任何nan值的iris_2d行

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])```

In [253]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

#方法1：
any_nan_in_row  = np.array([~np.any(np.isnan(row)) for row in iris_2d])
print(iris_2d[any_nan_in_row][:10])
#方法2：(By Rong)
iris_2d[np.sum(np.isnan(iris_2d), axis = 1) == 0][:10]

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]]


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2]])

**36.如何找到一个numpy数组的两列之间的相关性？** 

难度等级：L2 

问：在iris_2d中找到SepalLength（第一列）和PetalLength（第三列）之间的相关性 

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])```

In [267]:

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

#np.corrcoef(iris_2d[:,0],iris_2d[:,2])
sepalLength = iris_2d[:, 0]
petalLength = iris_2d[:, 2]
np.corrcoef(sepalLength, petalLength)[0,1]


0.8717541573048712

**37.如何查找给定数组是否具有空值？** 

难度等级：L2 

问：找出iris_2d是否有任何缺失值

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])```

In [268]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

np.any(np.isnan(iris_2d))#np.isnan(iris_2d).any()

False

**38.如何在numpy数组中将所有缺失值替换为0？** 

难度等级：L2 

问：numpy数组中，所有出现nan的都替换为0

输入：

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan```
    


In [271]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

iris_2d[np.isnan(iris_2d)] = 0
iris_2d[:5]

array([[5.1, 0. , 1.4, 0.2],
       [4.9, 3. , 1.4, 0. ],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0. ],
       [0. , 3.6, 1.4, 0.2]])

**39.如何在numpy数组中查找唯一值的计数？** 

难度等级：L2 

问：查找iris数据集species列的唯一值和唯一值的计数 

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [277]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = iris[:,4]
#species = np.array([row.tolist()[4] for row in iris])

np.unique(species, return_counts=True)

(array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'],
       dtype=object), array([50, 50, 50], dtype=int64))

**40.如何将数字转换为分类（文本）数组？** 

难度等级：L2 

问：对iris_2d的花瓣长度（第3列）进行装箱以形成文本数组，例如，如果花瓣长度为：

少于3->'小'

3-5->'中等'

'> = 5->'大' 


输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [287]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

# Bin petallength 
petal_length_bin = np.digitize(iris[:, 2].astype('float'), [0, 3, 5, 10])

# Map it to respective category
label_map = {1: 'small', 2: 'medium', 3: 'large', 4: np.nan}
petal_length_cat = [label_map[x] for x in petal_length_bin]

# View
petal_length_cat[:10]


['small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small',
 'small']

**41.如何从一个numpy数组的现有列中创建一个新列？** 

难度等级：L2 

问：在iris_2d中创建一个新列volume，其中volume的创建方式为 (pi * petallength * sepal_length^2)/3 

输入：

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [303]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

sepallength = iris_2d[:, 0].astype('float')
petallength = iris_2d[:, 2].astype('float')

#计算volume的值
volume = (np.pi * petallength * sepallength**2)/3

#将volume转换成2维，以匹配iris_2d的维数
#方法1：
volume_2d = np.tile(volume, (1,1)).reshape(-1,1)
#方法2：
#volume = volume[:, np.newaxis]

#纵向堆叠两个数组
new = np.hstack([iris_2d, volume_2d])
new[:5]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa',
        38.13265162927291],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa',
        35.200498485922445],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa', 30.0723720777127],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa',
        33.238050274980004],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa',
        36.65191429188092]], dtype=object)

**42.如何在numpy中进行概率抽样？** 

难度等级：L3 

Q.随机抽取iris的类别(species列)样本，使得setose类的数量是versicolor和virginica的和。
类别有：[b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica']

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [320]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

species = iris[:,4]
#print(species[:5])

#方法1：
a = np.array([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'])
sample = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])
#print(sample)

#方法2：???
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
print(index)
species_out = species[index]
print(species_out)
print(np.unique(species_out, return_counts=True))

[ 59  28  42 119   1  12  84 115  14  65 128  21  19  11  22 145 112  17
 113  27  43 138 114  33  18  37   1  25 109   2  70  71  11  38   4 128
 146   6 128  65  98  76  66   3  21  59 104  25  29 120 145 127  36  70
  35  34  18  24   5  51  37  69  76  14 136 139  70  39  36  21  28  25
  18 143 141  70  96  34  10  46  52   9  56 148  39  33 111 101  31  77
  58  30  11  31  45  82  25  78  20  81 106 106  72  31  89 122  75 146
 145  17   3  16 134 140  21  36  60  27  46  89  50  93  55   1  39  49
  40  35  50  44   9  27 138   3   4  28  67 148 148 148  11  83  55  17
 138  24 149  67  18  38]
[b'Iris-versicolor' b'Iris-setosa' b'Iris-setosa' b'Iris-virginica'
 b'Iris-setosa' b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica'
 b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica' b'Iris-setosa'
 b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-virginica'
 b'Iris-virginica' b'Iris-setosa' b'Iris-virginica' b'Iris-setosa'
 b'Iris-setosa' b'Iris-virginica' b'Iris-virginica' b'I

**43.当被另一个数组分组时，如何获得第二个最大值？** 

难度等级：L2 
 
问：物种setosa的petallength第二长是多少？

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [336]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

petal_len_setosa = iris[iris[:,4] == b'Iris-setosa',[2]]
np.unique(petal_len_setosa)[-2]

b'1.7'

**44.如何按列对二维数组排序** 

难度等级：L2 
 
问：根据sepallength列对iris数据集进行排序

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [337]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

iris[np.argsort(iris[:,0])][:4]

array([[b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'4.4', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'3.0', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa']], dtype=object)

**45.如何在numpy数组中查找最频繁的值？** 

难度等级：L1 

问：在iris数据集中找到最常见的花瓣长度值（第3列）

输入：

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

In [344]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

vals, counts = np.unique(iris[:,2], return_counts=True)
#print(vals, counts)
print(vals[np.argmax(counts)])

b'1.5'


**46.如何找到第一次出现的值大于给定值的位置？** 

难度等级：L2 

问：iris数据集第4列的花瓣宽度第一次出现的值大于1.0的位置 

输入： 

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')```

In [351]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

np.argwhere(iris[:, 3].astype('float') > 1.0)[0]

array([50], dtype=int64)

**47.如何将大于给定值的所有值替换为给定截止值？** 

难度等级：L2 

问：将数组a中所有大于30替换成30，小于10的值替换10，即按照给定值进行截断

输入：

```np.random.seed(100)
a = np.random.uniform(1,50, 20)```

In [355]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

#方法1：
np.where(a < 10,10,(np.where(a > 30,30,a)))

#方法2：
np.clip(a, a_min=10, a_max=30)


array([27.62684215, 14.64009987, 21.80136195, 30.        , 10.        ,
       10.        , 30.        , 30.        , 10.        , 29.17957314,
       30.        , 11.25090398, 10.08108276, 10.        , 11.76517714,
       30.        , 30.        , 10.        , 30.        , 14.42961361])

**48.如何从一个numpy数组中获取最高值的位置？** 

难度等级：L2 

问：获取给定数组a中前5个最大值的位置 

```np.random.seed(100)
a = np.random.uniform(1,50, 20)```

In [377]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)
print(np.argsort(a)[-5:])

# Below methods will get you the values.
# Method 1:
#a[a.argsort()][-5:]

# Method 2:
#np.sort(a)[-5:]

# Method 3:
#np.partition(a, kth=-5)[-5:]

# Method 4:
#a[np.argpartition(-a, 5)][:5]

[18  7  3 10 15]


**49.如何计算数组中所有可能值的按行计数？** 

难度等级：L4 

问：按行计算唯一值的计数 

输入：

/<code>
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
arr
> array([[ 9,  9,  4,  8,  8,  1,  5,  3,  6,  3],
>        [ 3,  3,  2,  1,  9,  5,  1, 10,  7,  3],
>        [ 5,  2,  6,  4,  5,  5,  4,  8,  2,  2],
>        [ 8,  8,  1,  3, 10, 10,  4,  3,  6,  9],
>        [ 2,  1,  8,  7,  3,  1,  9,  3,  6,  2],
>        [ 9,  2,  6,  5,  3,  9,  4,  6,  1, 10]])

期望的输出：

> [[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
>  [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
>  [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
>  [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
>  [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
>  [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]
/</code> 

输出包含10列，代表1到10之间的数字。值是相应行中数字的计数。 

例如，Cell（0,2）的值为2，这意味着数字3在第一行中恰好出现了2次。

In [393]:
np.random.seed(100)
arr = np.random.randint(1,11,size=(6, 10))
# Solution
def counts_of_all_values_rowwise(arr2d):
    # Unique values and its counts row wise
    num_counts_array = [np.unique(row, return_counts=True) for row in arr2d]
    #print(f"num_counts_array->{num_counts_array}")

    # Counts of all values row wise
    return([[int(b[a==i]) if i in a else 0 for i in np.unique(arr2d)] for a, b in num_counts_array])

# Print
print(np.arange(1,11))
counts_of_all_values_rowwise(arr)

#for i in np.unique(arr):
#    print(i)

[ 1  2  3  4  5  6  7  8  9 10]


[[1, 0, 2, 1, 1, 1, 0, 2, 2, 0],
 [2, 1, 3, 0, 1, 0, 1, 0, 1, 1],
 [0, 3, 0, 2, 3, 1, 0, 1, 0, 0],
 [1, 0, 2, 1, 0, 1, 0, 2, 1, 2],
 [2, 2, 2, 0, 0, 1, 1, 1, 1, 0],
 [1, 1, 1, 1, 1, 2, 0, 0, 2, 1]]

**50.如何将数组转换为平面一维数组？** 

难度等级：2 

问：将array_of_arrays转换为平面线性一维数组 

输入: 


```arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
array_of_arrays
#> array([array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])], dtype=object)
``` 

期望的输出：

`#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [394]:
 # Input:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
print('array_of_arrays: ', array_of_arrays)

# Solution 1
arr_2d = np.array([a for arr in array_of_arrays for a in arr])

# Solution 2:
arr_2d = np.concatenate(array_of_arrays)
print(arr_2d)

array_of_arrays:  [array([0, 1, 2]) array([3, 4, 5, 6]) array([7, 8, 9])]
[0 1 2 3 4 5 6 7 8 9]


c:\users\ifcreate-06\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:6: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  


**51.如何在numpy中为数组生成one-hot编码？** 

难度等级L4 

问：进行one-hot编码（数组中每个唯一值的虚拟二进制变量）

输入：

```np.random.seed(101) 
arr = np.random.randint(1,4, size=6)
arr
#> array([2, 3, 2, 2, 2, 1])``` 

输出：

```#> array([[ 0.,  1.,  0.],
#>        [ 0.,  0.,  1.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 0.,  1.,  0.],
#>        [ 1.,  0.,  0.]])```

In [428]:
np.random.seed(101)
arr = np.random.randint(1,4, size=6)
#print(arr.shape)

#方法1： 
def gen_one_hot(arr):
    print(arr)
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0],uniqs.shape[0]))
    i = 0
    for row in out:
        row[arr[i]-1] = 1
        i+=1
    return out
print(gen_one_hot(arr))

#方法2：
def one_hot_encodings(arr):
    uniqs = np.unique(arr)
    out = np.zeros((arr.shape[0], uniqs.shape[0]))
    for i, k in enumerate(arr):
        out[i, k-1] = 1
    return out
# 方法3:
(arr[:, None] == np.unique(arr)).view(np.int8)
print(arr[:, None] == np.unique(arr))

[2 3 2 2 2 1]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False  True False]
 [ True False False]]


**52.如何创建按类别变量分组的行号？** 

难度等级：L3 

问：创建按类别变量分组的行号。使用以下示例iris species作为输入。

输入：

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
       dtype='<U15')
``` 
    
期望的输出：

#> [0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 6, 7]

In [432]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)
print([i for val in np.unique(species_small) for i, grp in enumerate(species_small[species_small==val])])


['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5]


**53.如何基于给定的分类变量创建组ID？** 

难度等级：L4 

问：根据给定的分类变量创建组ID。使用以下示例iris species作为输入。

输入：

```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
species_small = np.sort(np.random.choice(species, size=20))
species_small
#> array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
#>        'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
#>        'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
#>        'Iris-virginica', 'Iris-virginica', 'Iris-virginica'],
#>       dtype='<U15')``` 


期望的输出：

#> [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]

In [455]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url, delimiter=',', dtype='str', usecols=4)
np.random.seed(100)
species_small = np.sort(np.random.choice(species, size=20))
print(species_small)
uniqs = np.unique(species_small)
out = []
for species in species_small:
    for uniq in uniqs:
        if species == uniq:
            out.append(np.argwhere(uniqs==species).tolist()[0][0])
print(out)
    

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-virginica' 'Iris-virginica' 'Iris-virginica'
 'Iris-virginica' 'Iris-virginica' 'Iris-virginica']
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]


**54.如何使用numpy对数组中的项目进行排名？** 

难度等级：L2 

问：为给定的数组a创建等级

输入：

```
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
#> [ 9  4 15  0 17 16 17  8  9  0]```

期望的输出：

[4 2 6 0 8 7 9 3 5 1]

In [463]:
np.random.seed(10)
a = np.random.randint(20, size=10)
print(a)
print(a.argsort().argsort())

[ 9  4 15  0 17 16 17  8  9  0]
[4 2 6 0 8 7 9 3 5 1]


**55.如何使用numpy对多维数组中的项目进行排名？** 

难度等级：L3 

问：创建与给定数值数组a形状相同的等级数组。

输入：

```np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
#> [[ 9  4 15  0 17]
#>  [16 17  8  9  0]]```

期望的输出：

#> [[4 2 6 0 8]
#>  [7 9 3 5 1]]

In [472]:
np.random.seed(10)
a = np.random.randint(20, size=[2,5])
print(a)
print(a.ravel().argsort().argsort().reshape(a.shape))

[[ 9  4 15  0 17]
 [16 17  8  9  0]]
[[4 2 6 0 8]
 [7 9 3 5 1]]


**56.如何在2维numpy数组的每一行中找到最大值？** 

难度等级：L2 

问：计算给定数组中每一行的最大值。

```np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])```

In [476]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)
print(np.max(a,axis=1))

# another Solution 1
print(np.amax(a, axis=1))

# another Solution 2
print(np.apply_along_axis(np.max, arr=a, axis=1))
#> array([9, 8, 6, 3, 9])

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[9 8 6 3 9]
[9 8 6 3 9]
[9 8 6 3 9]


**57.如何计算一个2维numpy数组的每一行的最小值与最大值之比？** 

难度等级：L3 

问：为给定的2d numpy数组计算每行的最小值与最大值之比。


```np.random.seed(100)
a = np.random.randint(1,10, [5,3])
a
#> array([[9, 9, 4],
#>        [8, 8, 1],
#>        [5, 3, 6],
#>        [3, 3, 3],
#>        [2, 1, 9]])```

In [479]:
np.random.seed(100)
a = np.random.randint(1,10, [5,3])
print(a)

print(np.apply_along_axis(lambda x:np.min(x)/np.max(x), arr=a, axis=1))

[[9 9 4]
 [8 8 1]
 [5 3 6]
 [3 3 3]
 [2 1 9]]
[0.44444444 0.125      0.5        1.         0.11111111]


**58.如何在numpy数组中查找重复记录？** 

难度等级：L3 

问：在给定的numpy数组中找到重复的条目（第二次出现），并将其标记为True。第一次出现应该是False。

输入： 

```np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#> Array: [0 0 3 0 2 4 2 2 2 2]```

期望的输出：

#> [False  True False  True False False  True  True  True  True]

In [501]:
# Input
np.random.seed(100)
a = np.random.randint(0, 5, 10)

## Solution
# There is no direct function to do this as of 1.13.3

# Create an all True array
out = np.full(a.shape[0], True)
print(out)

# Find the index positions of unique elements
unique_positions = np.unique(a, return_index=True)[1]
print(unique_positions)

# Mark those positions as False
out[unique_positions] = False

print(out)
    

[ True  True  True  True  True  True  True  True  True  True]
[0 4 2 5]
[False  True False  True False False  True  True  True  True]


**59.如何找到numpy中的分组均值？** 

难度等级:L3 

问：在二维numpy数组中找到按类别列分组的数字列的均值

输入：

```url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')```

期望的输出：

``` [[b'Iris-setosa', 3.418],
 [b'Iris-versicolor', 2.770],
 [b'Iris-virginica', 2.974]]```

In [6]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

numeric_column = iris[:, 1].astype('float')  # sepalwidth
grouping_column = iris[:, 4]  # species

out = []
for group_value in np.unique(grouping_column):
    print([group_value,numeric_column[grouping_column==group_value].mean()])

[b'Iris-setosa', 3.418]
[b'Iris-versicolor', 2.7700000000000005]
[b'Iris-virginica', 2.974]


**60.如何将PIL图像转换为numpy数组?** 

难度等级：L3 

问：从以下URL导入图像并将其转换为numpy数组。 

网址='https://gimg2.baidu.com/image_search/src=http%3A%2F%2Ftrekandmountain.com%2Fwp-content%2Fuploads%2F2017%2F04%2FDenali-Alamy-web-1014x400.jpg&refer=http%3A%2F%2Ftrekandmountain.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1624419757&t=881a756a8ddb880cbb4ee974dbdc2ac6'
##'https://upload.wikimedia.org/wikipedia/commons/8/8b/Denali_Mt_McKinley.jpg'

In [19]:
from io import BytesIO
from PIL import Image
import PIL, requests

URL = 'https://gimg2.baidu.com/image_search/src=http%3A%2F%2Ftrekandmountain.com%2Fwp-content%2Fuploads%2F2017%2F04%2FDenali-Alamy-web-1014x400.jpg&refer=http%3A%2F%2Ftrekandmountain.com&app=2002&size=f9999,10000&q=a80&n=0&g=0n&fmt=jpeg?sec=1624419757&t=881a756a8ddb880cbb4ee974dbdc2ac6'
response = requests.get(URL)

# Read it as Image and resize to 150*150
img = Image.open(BytesIO(response.content)).resize([150,150])
#convert to numpy array
arr = np.asarray(img)

#convert it back to an image and show 
img_back = Image.fromarray(np.uint8(arr))
Image.Image.show(img_back)

**61.如何从numpy数组中删除所有缺少的值？** 

难度等级：L2 

问：删除一维numpy数组中的所有nan值 

输入：

```
np.array([1,2,3,np.nan,5,6,7,np.nan])``` 


期望的输出： 
```array([ 1.,  2.,  3.,  5.,  6.,  7.])```

In [21]:
arr = np.array([1,2,3,np.nan,5,6,7,np.nan])
arr[~np.isnan(arr)]

array([1., 2., 3., 5., 6., 7.])

**62.如何计算两个数组之间的欧式距离？** 

难度等级：L3 

Q.计算两个numpy数组a和b之间的欧几里得距离。

输入：

a = np.array([1,2,3,4,5]) 

b = np.array([4,5,6,7,8])

In [26]:
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])

dist = np.linalg.norm(a-b)

**63.如何找到一维数组中的所有局部最大值（或峰值）？** 

难度等级：L4 

问：在一维numpy数组a中找到所有峰。峰值是两边都被较小值包围的点。

输入：

a = np.array([1, 3, 7, 1, 2, 6, 0, 1])

期望的输出：

#> array([2, 5])
其中2和5是峰值7和6的位置。

In [42]:
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
#方法一：
location=[]
for x in np.arange(len(a)-1) :
    if (a[x-1]  < a[x]) and ( a[x] > a[x+1]):
        location.append(x)
print(location)

#方法二：
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

[2, 5]


array([2, 5], dtype=int64)

## **64.如何从2d数组中减去1d数组，其中1d数组的每一项都从2d数组相应的行中减去？** 

难度等级：L2 

问：从2d数组a_2d中减去1d数组b_1d，以便从a_2d的相应行中减去b_1d的每一项。

```
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
b_1d = np.array([1,2,3])```

期望的输出：

``` [[2 2 2]
 [2 2 2]
 [2 2 2]]```

In [58]:
a_2d = np.array([[3,3,3],[4,4,4],[5,5,5]]) 
b_1d = np.array([1,2,3])
print(a_2d - b_1d.reshape(-1,1))

# Solution2
print(a_2d - b_1d[:,None])

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


**65.如何找到数组中第n个重复项的索引** 

难度等级:L2 

问：在x中找到数字1的第5个重复的索引 

x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [69]:
x = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])
n = 5
#方法1：
index = np.where(x==1)
print(index[0][n-1])
#方法2：
res = [i for i, v in enumerate(x) if v == 1][n-1]
print(res)

8
8


**66.如何将numpy的datetime64对象转换为datetime的datetime对象？** 

难度等级：L2 

问：将numpy的datetime64对象转换为datetime的datetime对象 

输入: 
```a numpy datetime64 object 
dt64 = np.datetime64（'2018-02-25 22:10:10' ）```

In [77]:
dt64 = np.datetime64('2018-02-25 22:10:10')
from datetime import datetime
print(dt64.tolist())

#or
print(dt64.astype(datetime))


2018-02-25 22:10:10
2018-02-25 22:10:10


**67.如何计算一个numpy数组的移动平均值？** 

难度等级：L3 

问：计算给定的一维数组的窗口大小3的移动平均值。

输入：

```
np.random.seed(100) 
Z = np.random.randint(10, size=10)```

In [91]:
np.random.seed(100) 
z = np.random.randint(10, size=10)
print(z)
n = 3
res = []
for i in np.arange(len(z)-(n-1)):
    j = i+n
    res.append(np.mean(z[i:j]))
print(res)
    
# another Solution
# Source: https://stackoverflow.com/questions/14313510/how-to-calculate-moving-average-using-numpy
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

np.random.seed(100)
Z = np.random.randint(10, size=10)
print('array: ', Z)
# Method 1
moving_average(Z, n=3).round(2)
# Method 2:  # Thanks AlanLRH!
# np.ones(3)/3 gives equal weights. Use np.ones(4)/4 for window size 4.
np.convolve(Z, np.ones(3)/3, mode='valid')

[8 8 3 7 7 0 4 2 5 2]
[6.333333333333333, 6.0, 5.666666666666667, 4.666666666666667, 3.6666666666666665, 2.0, 3.6666666666666665, 3.0]
array:  [8 8 3 7 7 0 4 2 5 2]


array([6.33333333, 6.        , 5.66666667, 4.66666667, 3.66666667,
       2.        , 3.66666667, 3.        ])

**68.如何仅给出起点，长度和步长来创建一个numpy数组序列？** 

难度等级：L2 

问：创建一个长度为10的numpy数组，从5开始，连续数字之间的步长为3 


In [92]:
length = 10
start = 5
step = 3

def seq(start, length, step):
    end = start + (step*length)
    return np.arange(start, end, step)
seq(start, length, step)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

**69.如何在不规则的一系列numpy日期中填写缺失的日期？** 

难度等级：L3 

问：给定一个非连续日期序列的数组。通过填写缺失的日期，使其成为连续的日期序列。

输入：

/<code>
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)
 ['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
'2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']
/</code>

In [96]:
dates = np.arange(np.datetime64('2018-02-01'), np.datetime64('2018-02-25'), 2)
print(dates)
dates_seq = np.arange(dates[0], dates[-1]+1)
print(dates_seq)

# Solution ---------------
filled_in = np.array([np.arange(date, (date+d)) for date, d in zip(dates, np.diff(dates))]).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
print(output)

# For loop version -------
out = []
for date, d in zip(dates, np.diff(dates)):
    out.append(np.arange(date, (date+d)))

filled_in = np.array(out).reshape(-1)

# add the last day
output = np.hstack([filled_in, dates[-1]])
print(output)

['2018-02-01' '2018-02-03' '2018-02-05' '2018-02-07' '2018-02-09'
 '2018-02-11' '2018-02-13' '2018-02-15' '2018-02-17' '2018-02-19'
 '2018-02-21' '2018-02-23']
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22' '2018-02-23']
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018-02-18' '2018-02-19' '2018-02-20'
 '2018-02-21' '2018-02-22' '2018-02-23']
['2018-02-01' '2018-02-02' '2018-02-03' '2018-02-04' '2018-02-05'
 '2018-02-06' '2018-02-07' '2018-02-08' '2018-02-09' '2018-02-10'
 '2018-02-11' '2018-02-12' '2018-02-13' '2018-02-14' '2018-02-15'
 '2018-02-16' '2018-02-17' '2018

**70.如何从给定的一维数组创建步幅指定的新数组？** 

难度等级：L4 

问：从给定的1d数组arr中，使用步幅生成2d矩阵，窗口长为4，步长为2，例如[[0,1,2,3]，[2,3,4,5]，[4 ，5,6,7] ..] 

输入：

```
arr = np.arange(15) 
arr
#> array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])```

In [111]:
arr = np.arange(15) 
print(f"arr is :\n{arr}")
kernel_size = 4
step = 2
res = []
print(f"start index is:\n{np.arange(len(arr)-(kernel_size-1),step = step)}")
for i in np.arange(len(arr)-(kernel_size-1),step = step):
    j = i+kernel_size
    res.append(np.array(arr[i:j]))
print(f"final seq is:\n{np.asarray(res)}")

# Solution ---------------
def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    # return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])
    return np.array([a[s:(s+window_len)] for s in np.arange(0, n_strides*stride_len, stride_len)])

print(gen_strides(np.arange(15), stride_len=2, window_len=4))


arr is :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
start index is:
[ 0  2  4  6  8 10]
final seq is:
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
[[ 0  1  2  3]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]]
